spring:
  application:
    name: integration_level
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
server:
  port: 8080
app:
  feign:
    customer:
      url: 127.0.0.1:8083
      path: /customer
    product:
      url: 127.0.0.1:8081
      path: /products
  jwt:
    signing-key: sdafjkaksdfjasdfjfasdklfjfkasdfjasdkfjfkasdfjfdsajsdsdafasdfasdfsdaff32rfafaffew
